language: node_js
node_js:
  - '8.12'
services:
  - docker
if: branch = feature/create-2019-docker
script:
  - cd 2019-dev
  - yarn install
  - yarn build
  - cd ../
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./.travis/docker_web_build.sh; fi
